### ISSUE TITLE
SSLError

### ISSUE THREAD

**Issue by wenjin11** [webrecorder/browsertrix-crawler#159] opened 2022-08-22 07:34 UTC
requests.exceptions.SSLError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /publicsuffix/list/master/public_suffix_list.dat (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:997)')))

**Comment by rgaudin** [comment] 2022-08-22 07:51
Looks like this belongs to zimit

**Comment by kelson42** [comment] 2023-05-22 09:38
@rgaudin Should we close this ticket (seems related to the setup, not to the data and we anyway have no way to reproduce it)? Or move it to `openzim/zimit`?

**Comment by rgaudin** [comment] 2023-05-22 09:49
We can't close tickets here ; that's why it's still there…

**Closed** 2023-05-22 15:37 UTC
